title: My Awesome Site
email: iam@thesigma.ca
description: "Nope"
baseurl: "" # the subpath of your site, e.g., /blog
url: "https://iamthesigma.github.io" # the base hostname & protocol for your site
