title: "Nope"
email: "iam@thesigma.ca"
description: "Nope"
baseurl: "" # No subpath if it's deployed at the root
url: "https://iamthesigma.github.io"

markdown: kramdown
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
